# 🐼 Pandas Sorting Data

In [1]:
import pandas as pd

employees = {
    "ID": [101, 102, 103, 104, 105, 106, 107],
    "Name": ["Alice", "Bob", "Charlie", "David", "Eva", "Frank", "Grace"],
    "Department": ["AI", "Web", "AI", "Data", "Web", "AI", "Data"],
    "Age": [24, 28, 26, 30, 25, 29, 27],
    "Salary": [90000, 70000, 85000, 95000, 65000, 92000, 88000],
    "Experience": [2, 4, 3, 6, 1, 5, 4]
}

df = pd.DataFrame(employees)

print(df)

    ID     Name Department  Age  Salary  Experience
0  101    Alice         AI   24   90000           2
1  102      Bob        Web   28   70000           4
2  103  Charlie         AI   26   85000           3
3  104    David       Data   30   95000           6
4  105      Eva        Web   25   65000           1
5  106    Frank         AI   29   92000           5
6  107    Grace       Data   27   88000           4

### 1️⃣ Basic Sorting

In [2]:
df.sort_values("Salary")

    ID     Name Department  Age  Salary  Experience
4  105      Eva        Web   25   65000           1
1  102      Bob        Web   28   70000           4
2  103  Charlie         AI   26   85000           3
6  107    Grace       Data   27   88000           4
0  101    Alice         AI   24   90000           2
5  106    Frank         AI   29   92000           5
3  104    David       Data   30   95000           6

### 2️⃣ Descending Order

In [3]:
df.sort_values("Salary", ascending=False)

    ID     Name Department  Age  Salary  Experience
3  104    David       Data   30   95000           6
5  106    Frank         AI   29   92000           5
0  101    Alice         AI   24   90000           2
6  107    Grace       Data   27   88000           4
2  103  Charlie         AI   26   85000           3
1  102      Bob        Web   28   70000           4
4  105      Eva        Web   25   65000           1

### 3️⃣ Sorting by Another Column

In [4]:
df.sort_values("Age")

    ID     Name Department  Age  Salary  Experience
0  101    Alice         AI   24   90000           2
4  105      Eva        Web   25   65000           1
2  103  Charlie         AI   26   85000           3
6  107    Grace       Data   27   88000           4
1  102      Bob        Web   28   70000           4
5  106    Frank         AI   29   92000           5
3  104    David       Data   30   95000           6

In [5]:
df.sort_values("Age", ascending=False)

    ID     Name Department  Age  Salary  Experience
3  104    David       Data   30   95000           6
5  106    Frank         AI   29   92000           5
1  102      Bob        Web   28   70000           4
6  107    Grace       Data   27   88000           4
2  103  Charlie         AI   26   85000           3
4  105      Eva        Web   25   65000           1
0  101    Alice         AI   24   90000           2

### 4️⃣ Sorting by Multiple Columns

In [6]:
df.sort_values(["Department", "Salary"])

    ID     Name Department  Age  Salary  Experience
2  103  Charlie         AI   26   85000           3
0  101    Alice         AI   24   90000           2
5  106    Frank         AI   29   92000           5
6  107    Grace       Data   27   88000           4
3  104    David       Data   30   95000           6
4  105      Eva        Web   25   65000           1
1  102      Bob        Web   28   70000           4

In [7]:
df.sort_values(["Department", "Salary"], ascending=False)

    ID     Name Department  Age  Salary  Experience
1  102      Bob        Web   28   70000           4
4  105      Eva        Web   25   65000           1
3  104    David       Data   30   95000           6
6  107    Grace       Data   27   88000           4
5  106    Frank         AI   29   92000           5
0  101    Alice         AI   24   90000           2
2  103  Charlie         AI   26   85000           3

### 5️⃣ Different Directions for Different Columns

In [8]:
df.sort_values(
    ["Department", "Salary"], 
    ascending=[True, False]
)

    ID     Name Department  Age  Salary  Experience
5  106    Frank         AI   29   92000           5
0  101    Alice         AI   24   90000           2
2  103  Charlie         AI   26   85000           3
3  104    David       Data   30   95000           6
6  107    Grace       Data   27   88000           4
1  102      Bob        Web   28   70000           4
4  105      Eva        Web   25   65000           1

### 8️⃣ Sorting After Filtering

In [9]:
df[
    (df["Department"] == "AI") & 
    (df["Salary"] > 80000)
].sort_values(
    "Salary",
    ascending=False
)

    ID     Name Department  Age  Salary  Experience
5  106    Frank         AI   29   92000           5
0  101    Alice         AI   24   90000           2
2  103  Charlie         AI   26   85000           3

### 9️⃣ inplace=True

In [11]:
df.sort_values("Salary", ascending=False, inplace=True)

df

    ID     Name Department  Age  Salary  Experience
3  104    David       Data   30   95000           6
5  106    Frank         AI   29   92000           5
0  101    Alice         AI   24   90000           2
6  107    Grace       Data   27   88000           4
2  103  Charlie         AI   26   85000           3
1  102      Bob        Web   28   70000           4
4  105      Eva        Web   25   65000           1

In [12]:
df.sort_values("ID", inplace=True)

df

    ID     Name Department  Age  Salary  Experience
0  101    Alice         AI   24   90000           2
1  102      Bob        Web   28   70000           4
2  103  Charlie         AI   26   85000           3
3  104    David       Data   30   95000           6
4  105      Eva        Web   25   65000           1
5  106    Frank         AI   29   92000           5
6  107    Grace       Data   27   88000           4

### Bonus

In [14]:
df.sort_values(
    "Experience",
    ascending=False
)[["Name", "Department", "Experience", "Salary"]].head(3)

    Name Department  Experience  Salary
3  David       Data           6   95000
5  Frank         AI           5   92000
1    Bob        Web           4   70000