# 🐼 Pandas EDA Assignment — Employee Analysis

### 📊 Dataset

In [49]:
import pandas as pd
import numpy as np

employees = {
    "ID": [201, 202, 203, 204, 205, 206, 207, 208],
    "Name": [
        "Aarav", "Meera", "Rohan", "Priya",
        "Arjun", "Ananya", "Kabir", "Ishita"
    ],
    "Department": [
        "AI", "Data", "Web", "AI",
        "Data", "AI", "Web", "Data"
    ],
    "Age": [23, 27, 31, 25, 29, 24, 28, 26],
    "Salary": [75000, 85000, 95000, 88000, 92000, 78000, 72000, 90000],
    "Experience": [1, 3, 7, 2, 5, 2, 4, 3],
    "Performance": [82, 91, 88, 95, 89, 84, 79, 93]
}

df = pd.DataFrame(employees)

print(df)

    ID    Name Department  Age  Salary  Experience  Performance
0  201   Aarav         AI   23   75000           1           82
1  202   Meera       Data   27   85000           3           91
2  203   Rohan        Web   31   95000           7           88
3  204   Priya         AI   25   88000           2           95
4  205   Arjun       Data   29   92000           5           89
5  206  Ananya         AI   24   78000           2           84
6  207   Kabir        Web   28   72000           4           79
7  208  Ishita       Data   26   90000           3           93

### 🟢 Part 1 — Understand the Dataset

In [50]:
print(df.shape[0])

8

In [51]:
print(df.shape[1])

7

In [52]:
print(df.dtypes)

## ["Name", "Department"] contain text

ID              int64
Name           object
Department     object
Age             int64
Salary          int64
Experience      int64
Performance     int64
dtype: object

In [53]:
print(df.head())
print()

print(df.tail())
print()

print(df.shape)
print()

print(df.dtypes)
print()

    ID   Name Department  Age  Salary  Experience  Performance
0  201  Aarav         AI   23   75000           1           82
1  202  Meera       Data   27   85000           3           91
2  203  Rohan        Web   31   95000           7           88
3  204  Priya         AI   25   88000           2           95
4  205  Arjun       Data   29   92000           5           89

    ID    Name Department  Age  Salary  Experience  Performance
3  204   Priya         AI   25   88000           2           95
4  205   Arjun       Data   29   92000           5           89
5  206  Ananya         AI   24   78000           2           84
6  207   Kabir        Web   28   72000           4           79
7  208  Ishita       Data   26   90000           3           93

(8, 7)

ID              int64
Name           object
Department     object
Age             int64
Salary          int64
Experience      int64
Performance     int64
dtype: object

### 🟢 Part 2 — Basic Analysis

In [54]:
average_salary = np.mean(df["Salary"])

print(average_salary)

84375.0

In [55]:
highest_salary = np.max(df["Salary"])

print(highest_salary)

95000

In [56]:
lowest_salary = np.min(df["Salary"])

print(lowest_salary)

72000

In [57]:
average_experience = np.mean(df["Experience"])

print(average_experience)

3.375

In [58]:
average_performance = np.mean(df["Performance"])

print(average_performance)

87.625

### 🟢 Part 3 — Filtering

In [59]:
df[df["Salary"] > 85000]

    ID    Name Department  Age  Salary  Experience  Performance
2  203   Rohan        Web   31   95000           7           88
3  204   Priya         AI   25   88000           2           95
4  205   Arjun       Data   29   92000           5           89
7  208  Ishita       Data   26   90000           3           93

In [60]:
df[df["Department"] == "AI"]

    ID    Name Department  Age  Salary  Experience  Performance
0  201   Aarav         AI   23   75000           1           82
3  204   Priya         AI   25   88000           2           95
5  206  Ananya         AI   24   78000           2           84

In [61]:
df[df["Experience"] >= 4]

    ID   Name Department  Age  Salary  Experience  Performance
2  203  Rohan        Web   31   95000           7           88
4  205  Arjun       Data   29   92000           5           89
6  207  Kabir        Web   28   72000           4           79

In [62]:
df[(df["Department"] == "AI") & (df["Salary"] > 80000)]

    ID   Name Department  Age  Salary  Experience  Performance
3  204  Priya         AI   25   88000           2           95

In [63]:
df[(df["Age"] < 27) & (df["Performance"] >= 90)]

    ID    Name Department  Age  Salary  Experience  Performance
3  204   Priya         AI   25   88000           2           95
7  208  Ishita       Data   26   90000           3           93

### 🟢 Part 4 — Create New Columns

In [64]:
df["Annual_Bonus"] = np.where(
    df["Salary"] >= 90000,
    10000,
    5000
)

df

    ID    Name Department  Age  Salary  Experience  Performance  Annual_Bonus
0  201   Aarav         AI   23   75000           1           82          5000
1  202   Meera       Data   27   85000           3           91          5000
2  203   Rohan        Web   31   95000           7           88         10000
3  204   Priya         AI   25   88000           2           95          5000
4  205   Arjun       Data   29   92000           5           89         10000
5  206  Ananya         AI   24   78000           2           84          5000
6  207   Kabir        Web   28   72000           4           79          5000
7  208  Ishita       Data   26   90000           3           93         10000

In [65]:
df["Total_Compensation"] = df["Salary"] + df["Annual_Bonus"]

df

,ID,Name,Department,Age,Salary,Experience,Performance,Annual_Bonus,Total_Compensation
0,201,Aarav,AI,23,75000,1,82,5000,80000
1,202,Meera,Data,27,85000,3,91,5000,90000
2,203,Rohan,Web,31,95000,7,88,10000,105000
3,204,Priya,AI,25,88000,2,95,5000,93000
4,205,Arjun,Data,29,92000,5,89,10000,102000
5,206,Ananya,AI,24,78000,2,84,5000,83000
6,207,Kabir,Web,28,72000,4,79,5000,77000
7,208,Ishita,Data,26,90000,3,93,10000,100000

In [66]:
df["Performance_Level"] = np.where(
    df["Performance"] >= 90,
    "Excellent",
    np.where(
        df["Performance"] >= 80,
        "Good",
        "Needs Improvement"
    )
)

df

,ID,Name,Department,Age,Salary,Experience,Performance,Annual_Bonus,Total_Compensation,Performance_Level
0,201,Aarav,AI,23,75000,1,82,5000,80000,Good
1,202,Meera,Data,27,85000,3,91,5000,90000,Excellent
2,203,Rohan,Web,31,95000,7,88,10000,105000,Good
3,204,Priya,AI,25,88000,2,95,5000,93000,Excellent
4,205,Arjun,Data,29,92000,5,89,10000,102000,Good
5,206,Ananya,AI,24,78000,2,84,5000,83000,Good
6,207,Kabir,Web,28,72000,4,79,5000,77000,Needs Improvement
7,208,Ishita,Data,26,90000,3,93,10000,100000,Excellent

### 🟢 Part 5 — Sorting

In [67]:
df.sort_values(
    "Salary",
    ascending=False
).head(3)

,ID,Name,Department,Age,Salary,Experience,Performance,Annual_Bonus,Total_Compensation,Performance_Level
2,203,Rohan,Web,31,95000,7,88,10000,105000,Good
4,205,Arjun,Data,29,92000,5,89,10000,102000,Good
7,208,Ishita,Data,26,90000,3,93,10000,100000,Excellent

In [68]:
df.sort_values(
    "Performance",
    ascending=False
).head(3)

,ID,Name,Department,Age,Salary,Experience,Performance,Annual_Bonus,Total_Compensation,Performance_Level
3,204,Priya,AI,25,88000,2,95,5000,93000,Excellent
7,208,Ishita,Data,26,90000,3,93,10000,100000,Excellent
1,202,Meera,Data,27,85000,3,91,5000,90000,Excellent

In [69]:
df.sort_values(
    ["Department", "Performance"],
    ascending=[True, False]
)

,ID,Name,Department,Age,Salary,Experience,Performance,Annual_Bonus,Total_Compensation,Performance_Level
3,204,Priya,AI,25,88000,2,95,5000,93000,Excellent
5,206,Ananya,AI,24,78000,2,84,5000,83000,Good
0,201,Aarav,AI,23,75000,1,82,5000,80000,Good
7,208,Ishita,Data,26,90000,3,93,10000,100000,Excellent
1,202,Meera,Data,27,85000,3,91,5000,90000,Excellent
4,205,Arjun,Data,29,92000,5,89,10000,102000,Good
2,203,Rohan,Web,31,95000,7,88,10000,105000,Good
6,207,Kabir,Web,28,72000,4,79,5000,77000,Needs Improvement

### 🟢 Part 6 — Combined EDA Questions

In [70]:
df[df["Department"] == "AI"].sort_values(
    "Salary",
    ascending=False
).head(1)

,ID,Name,Department,Age,Salary,Experience,Performance,Annual_Bonus,Total_Compensation,Performance_Level
3,204,Priya,AI,25,88000,2,95,5000,93000,Excellent

In [71]:
df[(df["Experience"] >= 3) & (df["Performance"] >= 90)].sort_values(
    "Performance",
    ascending=False
)

,ID,Name,Department,Age,Salary,Experience,Performance,Annual_Bonus,Total_Compensation,Performance_Level
7,208,Ishita,Data,26,90000,3,93,10000,100000,Excellent
1,202,Meera,Data,27,85000,3,91,5000,90000,Excellent

In [72]:
df.sort_values(
    "Total_Compensation",
    ascending=False
).head(1)

,ID,Name,Department,Age,Salary,Experience,Performance,Annual_Bonus,Total_Compensation,Performance_Level
2,203,Rohan,Web,31,95000,7,88,10000,105000,Good

In [73]:
print(df[df["Department"] == "AI"]["Salary"].mean())

80333.33333333333

In [74]:
total_employees = df[(df["Salary"] >= 85000) & (df["Performance"] >= 85)].sort_values(
    "Performance",
    ascending=False
)[["Name", "Department", "Salary", "Performance", "Total_Compensation"]]

total_employees

     Name Department  Salary  Performance  Total_Compensation
3   Priya         AI   88000           95               93000
7  Ishita       Data   90000           93              100000
1   Meera       Data   85000           91               90000
4   Arjun       Data   92000           89              102000
2   Rohan        Web   95000           88              105000