# 🐼 Pandas: groupby() + Aggregation

### 1️⃣ What is groupby()?

In [1]:
import pandas as pd

employees = {
    "Name": ["A", "B", "C", "D", "E", "F"],
    "Department": ["AI", "AI", "Data", "Data", "Web", "Web"],
    "Salary": [80000, 90000, 70000, 85000, 60000, 75000],
    "Performance": [85, 95, 80, 90, 75, 88]
}

df = pd.DataFrame(employees)

In [4]:
df.groupby("Department")

### 2️⃣ groupby() + mean()

In [5]:
df.groupby("Department")["Salary"].mean()

Department
AI      85000.0
Data    77500.0
Web     67500.0
Name: Salary, dtype: float64

### 3️⃣ Other aggregation functions

In [6]:
df.groupby("Department")["Salary"].max()

Department
AI      90000
Data    85000
Web     75000
Name: Salary, dtype: int64

In [7]:
df.groupby("Department")["Salary"].min()

Department
AI      80000
Data    70000
Web     60000
Name: Salary, dtype: int64

In [8]:
df.groupby("Department")["Salary"].sum()

Department
AI      170000
Data    155000
Web     135000
Name: Salary, dtype: int64

In [9]:
df.groupby("Department")["Salary"].count()

Department
AI      2
Data    2
Web     2
Name: Salary, dtype: int64

### 4️⃣ Grouping without selecting a column

In [10]:
df.groupby("Department").mean(numeric_only=True)

             Salary  Performance
Department
AI          85000.0         90.0
Data        77500.0         85.0
Web         67500.0         81.5

### 5️⃣ agg() — Multiple calculations at once

In [12]:
df.groupby("Department")["Salary"].agg(
    ["mean", "max", "min"]
)

               mean    max    min
Department
AI          85000.0  90000  80000
Data        77500.0  85000  70000
Web         67500.0  75000  60000

### 6️⃣ Different aggregations for different columns

In [14]:
df.groupby("Department").agg({
    "Salary": ["mean", "max"],
    "Performance": ["mean", "max", "min"]
})

             Salary        Performance
               mean    max        mean max min
Department
AI          85000.0  90000        90.0  95  85
Data        77500.0  85000        85.0  90  80
Web         67500.0  75000        81.5  88  75

### 7️⃣ groupby() with multiple columns

In [15]:
df.groupby(["Department", "Performance"])

### 8️⃣ Getting a normal DataFrame back

In [21]:
result = df.groupby("Department")["Salary"].mean()


result = result.reset_index()

result

Department
AI      85000.0
Data    77500.0
Web     67500.0
Name: Salary, dtype: float64