# 🐼 Pandas: Duplicates + replace() + rename()

In [1]:
import pandas as pd
import numpy as np

employees = {
    "Employee_ID": [
        501, 502, 503, 504, 505,
        506, 507, 508, 509, 510,
        510, 503
    ],

    "Employee_Name": [
        "Aarav", "Meera", "Rohan", "Priya", "Arjun",
        "Ananya", "Kabir", "Ishita", "Rahul", "Sneha",
        "Sneha", "Rohan"
    ],

    "Department": [
        "AI", "Data", "AI", "Artificial Intelligence",
        "Data", "AI", "Web", "Web",
        "AI", "Data", "Data", "AI"
    ],

    "City": [
        "Delhi", "Mumbai", "Delhi", "Pune",
        "Mumbai", "Delhi", "Pune", "Mumbai",
        "Delhi", "Pune", "Pune", "Delhi"
    ],

    "Salary": [
        78000, 85000, 92000, 68000,
        91000, 88000, 72000, 95000,
        105000, 70000, 70000, 92000
    ],

    "Performance": [
        82, 91, 88, 95,
        89, 84, 79, 93,
        97, 81, 81, 88
    ]
}

df = pd.DataFrame(employees)

print(df)

    Employee_ID Employee_Name               Department    City  Salary  \
0           501         Aarav                       AI   Delhi   78000
1           502         Meera                     Data  Mumbai   85000
2           503         Rohan                       AI   Delhi   92000
3           504         Priya  Artificial Intelligence    Pune   68000
4           505         Arjun                     Data  Mumbai   91000
5           506        Ananya                       AI   Delhi   88000
6           507         Kabir                      Web    Pune   72000
7           508        Ishita                      Web  Mumbai   95000
8           509         Rahul                       AI   Delhi  105000
9           510         Sneha                     Data    Pune   70000
10          510         Sneha                     Data    Pune   70000
11          503         Rohan                       AI   Delhi   92000

    Performance
0            82
1            91
2            88
3            95
4            89
5            84
6            79
7            93
8            97
9            81
10           81
11           88

### 1. duplicated()

In [2]:
df.duplicated()

0     False
1     False
2     False
3     False
4     False
5     False
6     False
7     False
8     False
9     False
10     True
11     True
dtype: bool

In [4]:
print(df.duplicated().sum())

2

### 2. drop_duplicates()

In [5]:
df.drop_duplicates()

,Employee_ID,Employee_Name,Department,City,Salary,Performance
0,501,Aarav,AI,Delhi,78000,82
1,502,Meera,Data,Mumbai,85000,91
2,503,Rohan,AI,Delhi,92000,88
3,504,Priya,Artificial Intelligence,Pune,68000,95
4,505,Arjun,Data,Mumbai,91000,89
5,506,Ananya,AI,Delhi,88000,84
6,507,Kabir,Web,Pune,72000,79
7,508,Ishita,Web,Mumbai,95000,93
8,509,Rahul,AI,Delhi,105000,97
9,510,Sneha,Data,Pune,70000,81

### 3. Duplicates based on a specific column

In [8]:
df.duplicated(subset=["Employee_ID"])

0     False
1     False
2     False
3     False
4     False
5     False
6     False
7     False
8     False
9     False
10     True
11     True
dtype: bool

### 4. replace()

In [10]:
df["Department"] = df["Department"].replace(
    "Artificial Intelligence",
    "AI"
)

df

    Employee_ID Employee_Name Department    City  Salary  Performance
0           501         Aarav         AI   Delhi   78000           82
1           502         Meera       Data  Mumbai   85000           91
2           503         Rohan         AI   Delhi   92000           88
3           504         Priya         AI    Pune   68000           95
4           505         Arjun       Data  Mumbai   91000           89
5           506        Ananya         AI   Delhi   88000           84
6           507         Kabir        Web    Pune   72000           79
7           508        Ishita        Web  Mumbai   95000           93
8           509         Rahul         AI   Delhi  105000           97
9           510         Sneha       Data    Pune   70000           81
10          510         Sneha       Data    Pune   70000           81
11          503         Rohan         AI   Delhi   92000           88

### 5. rename()

In [12]:
df = df.rename(columns={
    "Employee_ID": "ID",
    "Employee_Name": "Name"
})

df

     ID    Name Department    City  Salary  Performance
0   501   Aarav         AI   Delhi   78000           82
1   502   Meera       Data  Mumbai   85000           91
2   503   Rohan         AI   Delhi   92000           88
3   504   Priya         AI    Pune   68000           95
4   505   Arjun       Data  Mumbai   91000           89
5   506  Ananya         AI   Delhi   88000           84
6   507   Kabir        Web    Pune   72000           79
7   508  Ishita        Web  Mumbai   95000           93
8   509   Rahul         AI   Delhi  105000           97
9   510   Sneha       Data    Pune   70000           81
10  510   Sneha       Data    Pune   70000           81
11  503   Rohan         AI   Delhi   92000           88

In [13]:
df = df.drop_duplicates()

In [14]:
df

    ID    Name Department    City  Salary  Performance
0  501   Aarav         AI   Delhi   78000           82
1  502   Meera       Data  Mumbai   85000           91
2  503   Rohan         AI   Delhi   92000           88
3  504   Priya         AI    Pune   68000           95
4  505   Arjun       Data  Mumbai   91000           89
5  506  Ananya         AI   Delhi   88000           84
6  507   Kabir        Web    Pune   72000           79
7  508  Ishita        Web  Mumbai   95000           93
8  509   Rahul         AI   Delhi  105000           97
9  510   Sneha       Data    Pune   70000           81