# 🏢 Mini-Project: Employee Data Analysis

### Create the dataset

In [90]:
import pandas as pd
import numpy as np

employees = {
    "Employee_ID": [
        601, 602, 603, 604, 605,
        606, 607, 608, 609, 610,
        610, 603
    ],

    "Name": [
        "Aarav", "Meera", "Rohan", "Priya", "Arjun",
        "Ananya", "Kabir", "Ishita", "Rahul", "Sneha",
        "Sneha", "Rohan"
    ],

    "Department": [
        "AI", "Data", "AI", "Artificial Intelligence",
        "Data", "AI", "Web", "Web",
        np.nan, "Data", "Data", "AI"
    ],

    "City": [
        "Delhi", "Mumbai", "Delhi", "Pune",
        "Mumbai", "Delhi", "Pune", "Mumbai",
        "Delhi", "Pune", "Pune", "Delhi"
    ],

    "Age": [
        24, 27, np.nan, 25, 29,
        23, 28, 26, 30, np.nan,
        np.nan, 31
    ],

    "Salary": [
        78000, 85000, 92000, np.nan,
        91000, 88000, 72000, 95000,
        105000, 70000, 70000, 92000
    ],

    "Experience": [
        1, 3, 7, 2, np.nan,
        2, 4, 6, 8, 1,
        1, 7
    ],

    "Performance": [
        82, 91, 88, 95, 89,
        84, 79, 93, 97, np.nan,
        np.nan, 88
    ]
}

df = pd.DataFrame(employees)

print(df)

    Employee_ID    Name               Department    City   Age    Salary  \
0           601   Aarav                       AI   Delhi  24.0   78000.0
1           602   Meera                     Data  Mumbai  27.0   85000.0
2           603   Rohan                       AI   Delhi   NaN   92000.0
3           604   Priya  Artificial Intelligence    Pune  25.0       NaN
4           605   Arjun                     Data  Mumbai  29.0   91000.0
5           606  Ananya                       AI   Delhi  23.0   88000.0
6           607   Kabir                      Web    Pune  28.0   72000.0
7           608  Ishita                      Web  Mumbai  26.0   95000.0
8           609   Rahul                      NaN   Delhi  30.0  105000.0
9           610   Sneha                     Data    Pune   NaN   70000.0
10          610   Sneha                     Data    Pune   NaN   70000.0
11          603   Rohan                       AI   Delhi  31.0   92000.0

    Experience  Performance
0          1.0         82.0
1          3.0         91.0
2          7.0         88.0
3          2.0         95.0
4          NaN         89.0
5          2.0         84.0
6          4.0         79.0
7          6.0         93.0
8          8.0         97.0
9          1.0          NaN
10         1.0          NaN
11         7.0         88.0

### Part 1 — Create the cleaning pipeline

In [91]:
clean_df = df.copy()

### Part 2 — Data Cleaning

In [92]:
clean_df.isnull()

,Employee_ID,Name,Department,City,Age,Salary,Experience,Performance
0,False,False,False,False,False,False,False,False
1,False,False,False,False,False,False,False,False
2,False,False,False,False,True,False,False,False
3,False,False,False,False,False,True,False,False
4,False,False,False,False,False,False,True,False
5,False,False,False,False,False,False,False,False
6,False,False,False,False,False,False,False,False
7,False,False,False,False,False,False,False,False
8,False,False,True,False,False,False,False,False
9,False,False,False,False,True,False,False,True
10,False,False,False,False,True,False,False,True
11,False,False,False,False,False,False,False,False

In [93]:
clean_df["Department"] = clean_df["Department"].fillna(
    clean_df["Department"].mode()[0]
)

In [94]:
clean_df["Age"] = clean_df["Age"].fillna(
    clean_df["Age"].mean()
)

In [95]:
clean_df["Salary"] = clean_df["Salary"].fillna(
    clean_df["Salary"].median()
)

In [96]:
clean_df["Experience"] = clean_df["Experience"].fillna(
    clean_df["Experience"].mean()
)

In [97]:
clean_df["Performance"] = clean_df["Performance"].fillna(
    clean_df["Performance"].mean()
)

In [98]:
clean_df.isnull()

,Employee_ID,Name,Department,City,Age,Salary,Experience,Performance
0,False,False,False,False,False,False,False,False
1,False,False,False,False,False,False,False,False
2,False,False,False,False,False,False,False,False
3,False,False,False,False,False,False,False,False
4,False,False,False,False,False,False,False,False
5,False,False,False,False,False,False,False,False
6,False,False,False,False,False,False,False,False
7,False,False,False,False,False,False,False,False
8,False,False,False,False,False,False,False,False
9,False,False,False,False,False,False,False,False
10,False,False,False,False,False,False,False,False
11,False,False,False,False,False,False,False,False

In [99]:
clean_df.duplicated()

0     False
1     False
2     False
3     False
4     False
5     False
6     False
7     False
8     False
9     False
10     True
11    False
dtype: bool

In [100]:
clean_df["Department"] = clean_df["Department"].replace(
    "Artificial Intelligence",
    "AI"
)

In [101]:
clean_df = clean_df.rename(columns={
    "Employee_ID": "ID"
})

In [102]:
clean_df = clean_df.drop_duplicates(
    subset="ID",
    keep="first"
)

In [103]:
clean_df

    ID    Name Department    City   Age    Salary  Experience  Performance
0  601   Aarav         AI   Delhi  24.0   78000.0    1.000000         82.0
1  602   Meera       Data  Mumbai  27.0   85000.0    3.000000         91.0
2  603   Rohan         AI   Delhi  27.0   92000.0    7.000000         88.0
3  604   Priya         AI    Pune  25.0   88000.0    2.000000         95.0
4  605   Arjun       Data  Mumbai  29.0   91000.0    3.818182         89.0
5  606  Ananya         AI   Delhi  23.0   88000.0    2.000000         84.0
6  607   Kabir        Web    Pune  28.0   72000.0    4.000000         79.0
7  608  Ishita        Web  Mumbai  26.0   95000.0    6.000000         93.0
8  609   Rahul         AI   Delhi  30.0  105000.0    8.000000         97.0
9  610   Sneha       Data    Pune  27.0   70000.0    1.000000         88.6

### 📊 Part 3 — EDA

In [104]:
print(clean_df["Salary"].mean())

86400.0

In [105]:
print(clean_df["Salary"].median())

88000.0

In [106]:
print(clean_df["Salary"].max())

105000.0

In [107]:
print(clean_df["Salary"].min())

70000.0

In [108]:
clean_df.groupby("Department")["Salary"].mean()

Department
AI      90200.0
Data    82000.0
Web     83500.0
Name: Salary, dtype: float64

In [109]:
clean_df.groupby("Department")["Performance"].mean()

Department
AI      89.200000
Data    89.533333
Web     86.000000
Name: Performance, dtype: float64

In [110]:
clean_df.groupby("Department")["Salary"].count()

Department
AI      5
Data    3
Web     2
Name: Salary, dtype: int64

In [111]:
clean_df.sort_values(
    "Salary",
    ascending=False
).head(3)

    ID    Name Department    City   Age    Salary  Experience  Performance
8  609   Rahul         AI   Delhi  30.0  105000.0         8.0         97.0
7  608  Ishita        Web  Mumbai  26.0   95000.0         6.0         93.0
2  603   Rohan         AI   Delhi  27.0   92000.0         7.0         88.0

In [112]:
clean_df.sort_values(
    "Performance",
    ascending=False
).head(3)

    ID    Name Department    City   Age    Salary  Experience  Performance
8  609   Rahul         AI   Delhi  30.0  105000.0         8.0         97.0
3  604   Priya         AI    Pune  25.0   88000.0         2.0         95.0
7  608  Ishita        Web  Mumbai  26.0   95000.0         6.0         93.0

In [113]:
clean_df["Annual_Bonus"] = np.where(
    clean_df["Salary"] >= 90000,
    10000,
    5000
)

clean_df["Total_Compensation"] = clean_df["Salary"] + clean_df["Annual_Bonus"]

clean_df

,ID,Name,Department,City,Age,Salary,Experience,Performance,Annual_Bonus,Total_Compensation
0,601,Aarav,AI,Delhi,24.0,78000.0,1.000000,82.0,5000,83000.0
1,602,Meera,Data,Mumbai,27.0,85000.0,3.000000,91.0,5000,90000.0
2,603,Rohan,AI,Delhi,27.0,92000.0,7.000000,88.0,10000,102000.0
3,604,Priya,AI,Pune,25.0,88000.0,2.000000,95.0,5000,93000.0
4,605,Arjun,Data,Mumbai,29.0,91000.0,3.818182,89.0,10000,101000.0
5,606,Ananya,AI,Delhi,23.0,88000.0,2.000000,84.0,5000,93000.0
6,607,Kabir,Web,Pune,28.0,72000.0,4.000000,79.0,5000,77000.0
7,608,Ishita,Web,Mumbai,26.0,95000.0,6.000000,93.0,10000,105000.0
8,609,Rahul,AI,Delhi,30.0,105000.0,8.000000,97.0,10000,115000.0
9,610,Sneha,Data,Pune,27.0,70000.0,1.000000,88.6,5000,75000.0

In [114]:
clean_df["Performance_Level"] = np.where(
    clean_df["Performance"] >= 90,
    "Excellent",
    np.where(
        clean_df["Performance"] >= 80,
        "Good",
        "Needs Improvement"
    )
)

clean_df

,ID,Name,Department,City,Age,Salary,Experience,Performance,Annual_Bonus,Total_Compensation,Performance_Level
0,601,Aarav,AI,Delhi,24.0,78000.0,1.000000,82.0,5000,83000.0,Good
1,602,Meera,Data,Mumbai,27.0,85000.0,3.000000,91.0,5000,90000.0,Excellent
2,603,Rohan,AI,Delhi,27.0,92000.0,7.000000,88.0,10000,102000.0,Good
3,604,Priya,AI,Pune,25.0,88000.0,2.000000,95.0,5000,93000.0,Excellent
4,605,Arjun,Data,Mumbai,29.0,91000.0,3.818182,89.0,10000,101000.0,Good
5,606,Ananya,AI,Delhi,23.0,88000.0,2.000000,84.0,5000,93000.0,Good
6,607,Kabir,Web,Pune,28.0,72000.0,4.000000,79.0,5000,77000.0,Needs Improvement
7,608,Ishita,Web,Mumbai,26.0,95000.0,6.000000,93.0,10000,105000.0,Excellent
8,609,Rahul,AI,Delhi,30.0,105000.0,8.000000,97.0,10000,115000.0,Excellent
9,610,Sneha,Data,Pune,27.0,70000.0,1.000000,88.6,5000,75000.0,Good

In [115]:
result = clean_df.groupby("Department")["Salary"].mean()
result = result.reset_index()

result

  Department   Salary
0         AI  90200.0
1       Data  82000.0
2        Web  83500.0

In [116]:
result.sort_values(
    "Salary",
    ascending=False
).head(1)

  Department   Salary
0         AI  90200.0

In [117]:
result = clean_df.groupby("Department")["Performance"].mean()
result = result.reset_index()

result

  Department  Performance
0         AI    89.200000
1       Data    89.533333
2        Web    86.000000

In [118]:
result.sort_values(
    "Performance",
    ascending=False
).head(1)

  Department  Performance
1       Data    89.533333

In [119]:
summary = clean_df.groupby("Department").agg(
    Employee_Count=("ID", "count"),
    Average_Salary=("Salary", "mean"),
    Average_Performance=("Performance", "mean"),
    Maximum_Salary=("Salary", "max")
)

summary = summary.sort_values(
    "Average_Salary",
    ascending=False
)

summary

,Employee_Count,Average_Salary,Average_Performance,Maximum_Salary
Department,,,,
AI,5,90200.0,89.200000,105000.0
Web,2,83500.0,86.000000,95000.0
Data,3,82000.0,89.533333,91000.0

In [121]:
final_summary = clean_df.sort_values(
    "Total_Compensation",
    ascending=False
)[[
    "ID",
    "Name",
    "Department",
    "City",
    "Age",
    "Salary",
    "Experience",
    "Performance",
    "Annual_Bonus",
    "Total_Compensation",
    "Performance_Level"
]]

final_summary

,ID,Name,Department,City,Age,Salary,Experience,Performance,Annual_Bonus,Total_Compensation,Performance_Level
8,609,Rahul,AI,Delhi,30.0,105000.0,8.000000,97.0,10000,115000.0,Excellent
7,608,Ishita,Web,Mumbai,26.0,95000.0,6.000000,93.0,10000,105000.0,Excellent
2,603,Rohan,AI,Delhi,27.0,92000.0,7.000000,88.0,10000,102000.0,Good
4,605,Arjun,Data,Mumbai,29.0,91000.0,3.818182,89.0,10000,101000.0,Good
3,604,Priya,AI,Pune,25.0,88000.0,2.000000,95.0,5000,93000.0,Excellent
5,606,Ananya,AI,Delhi,23.0,88000.0,2.000000,84.0,5000,93000.0,Good
1,602,Meera,Data,Mumbai,27.0,85000.0,3.000000,91.0,5000,90000.0,Excellent
0,601,Aarav,AI,Delhi,24.0,78000.0,1.000000,82.0,5000,83000.0,Good
6,607,Kabir,Web,Pune,28.0,72000.0,4.000000,79.0,5000,77000.0,Needs Improvement
9,610,Sneha,Data,Pune,27.0,70000.0,1.000000,88.6,5000,75000.0,Good