# 🐼 Missing Data

### 1️⃣ Create a Dataset

In [1]:
import pandas as pd
import numpy as np

employees = {
    "Name": ["Alice", "Bob", "Charlie", "David", "Eva", "Frank"],
    "Age": [24, np.nan, 26, 30, np.nan, 29],
    "Department": ["AI", "Data", np.nan, "AI", "Web", "Data"],
    "Salary": [90000, 75000, np.nan, 95000, 65000, np.nan],
    "Experience": [2, 4, 3, np.nan, 1, 5]
}

df = pd.DataFrame(employees)

print(df)

      Name   Age Department   Salary  Experience
0    Alice  24.0         AI  90000.0         2.0
1      Bob   NaN       Data  75000.0         4.0
2  Charlie  26.0        NaN      NaN         3.0
3    David  30.0         AI  95000.0         NaN
4      Eva   NaN        Web  65000.0         1.0
5    Frank  29.0       Data      NaN         5.0

### 2️⃣ Detect Missing Values

In [2]:
df.isnull()

    Name    Age  Department  Salary  Experience
0  False  False       False   False       False
1  False   True       False   False       False
2  False  False        True    True       False
3  False  False       False   False        True
4  False   True       False   False       False
5  False  False       False    True       False

### 3️⃣ Count Missing Values

In [3]:
df.isnull().sum()

Name          0
Age           2
Department    1
Salary        2
Experience    1
dtype: int64

### 4️⃣ Find Rows Containing Missing Values

In [6]:
df[df.isnull().any(axis=1)]

      Name   Age Department   Salary  Experience
1      Bob   NaN       Data  75000.0         4.0
2  Charlie  26.0        NaN      NaN         3.0
3    David  30.0         AI  95000.0         NaN
4      Eva   NaN        Web  65000.0         1.0
5    Frank  29.0       Data      NaN         5.0

### 5️⃣ Find Rows With No Missing Values

In [9]:
df[df.notnull().all(axis=1)]

    Name   Age Department   Salary  Experience
0  Alice  24.0         AI  90000.0         2.0

### 6️⃣ Dropping Missing Values

In [8]:
df.dropna()

    Name   Age Department   Salary  Experience
0  Alice  24.0         AI  90000.0         2.0

### 7️⃣ Filling Missing Values

In [11]:
df["Age"] = df["Age"].fillna(df["Age"].mean())

df

      Name    Age Department   Salary  Experience
0    Alice  24.00         AI  90000.0         2.0
1      Bob  27.25       Data  75000.0         4.0
2  Charlie  26.00        NaN      NaN         3.0
3    David  30.00         AI  95000.0         NaN
4      Eva  27.25        Web  65000.0         1.0
5    Frank  29.00       Data      NaN         5.0

In [13]:
df["Salary"] = df["Salary"].fillna(df["Salary"].mean())

df

      Name    Age Department   Salary  Experience
0    Alice  24.00         AI  90000.0         2.0
1      Bob  27.25       Data  75000.0         4.0
2  Charlie  26.00        NaN  81250.0         3.0
3    David  30.00         AI  95000.0         NaN
4      Eva  27.25        Web  65000.0         1.0
5    Frank  29.00       Data  81250.0         5.0

In [15]:
df["Department"] = df["Department"].fillna(
    df["Department"].mode()[0]
)

df

      Name    Age Department   Salary  Experience
0    Alice  24.00         AI  90000.0         2.0
1      Bob  27.25       Data  75000.0         4.0
2  Charlie  26.00         AI  81250.0         3.0
3    David  30.00         AI  95000.0         NaN
4      Eva  27.25        Web  65000.0         1.0
5    Frank  29.00       Data  81250.0         5.0

In [16]:
df.isnull().sum()

Name          0
Age           0
Department    0
Salary        0
Experience    1
dtype: int64

In [18]:
df["Experience"] = df["Experience"].fillna(df["Experience"].mean())

df

      Name    Age Department   Salary  Experience
0    Alice  24.00         AI  90000.0         2.0
1      Bob  27.25       Data  75000.0         4.0
2  Charlie  26.00         AI  81250.0         3.0
3    David  30.00         AI  95000.0         3.0
4      Eva  27.25        Web  65000.0         1.0
5    Frank  29.00       Data  81250.0         5.0

In [19]:
df.isnull().sum()

Name          0
Age           0
Department    0
Salary        0
Experience    0
dtype: int64