# 🐼 Handling Missing Data in Pandas

In [10]:
import pandas as pd
import numpy as np

employees = {
    "Name": ["Alice", "Bob", "Charlie", "David", "Eva", "Frank"],
    "Age": [24, np.nan, 26, 30, np.nan, 29],
    "Department": ["AI", "Data", np.nan, "AI", "Web", "Data"],
    "Salary": [90000, 75000, np.nan, 95000, 65000, np.nan],
    "Experience": [2, 4, 3, np.nan, 1, 5]
}

df = pd.DataFrame(employees)

print(df)

      Name   Age Department   Salary  Experience
0    Alice  24.0         AI  90000.0         2.0
1      Bob   NaN       Data  75000.0         4.0
2  Charlie  26.0        NaN      NaN         3.0
3    David  30.0         AI  95000.0         NaN
4      Eva   NaN        Web  65000.0         1.0
5    Frank  29.0       Data      NaN         5.0

### 1️⃣ dropna() — Remove Missing Rows

In [11]:
df.dropna()

    Name   Age Department   Salary  Experience
0  Alice  24.0         AI  90000.0         2.0

### 2️⃣ Drop Rows Only When a Specific Column Is Missing

In [12]:
df.dropna(subset="Salary")

    Name   Age Department   Salary  Experience
0  Alice  24.0         AI  90000.0         2.0
1    Bob   NaN       Data  75000.0         4.0
3  David  30.0         AI  95000.0         NaN
4    Eva   NaN        Web  65000.0         1.0

### 3️⃣ fillna() — Replace Missing Values

In [13]:
df["Age"] = df["Age"].fillna(df["Age"].mean())

df

      Name    Age Department   Salary  Experience
0    Alice  24.00         AI  90000.0         2.0
1      Bob  27.25       Data  75000.0         4.0
2  Charlie  26.00        NaN      NaN         3.0
3    David  30.00         AI  95000.0         NaN
4      Eva  27.25        Web  65000.0         1.0
5    Frank  29.00       Data      NaN         5.0

### 4️⃣ Median Instead of Mean

In [14]:
df["Salary"].fillna(df["Salary"].median())

0    90000.0
1    75000.0
2    82500.0
3    95000.0
4    65000.0
5    82500.0
Name: Salary, dtype: float64

### 5️⃣ Forward Fill

In [15]:
df["Salary"].ffill()

0    90000.0
1    75000.0
2    75000.0
3    95000.0
4    65000.0
5    65000.0
Name: Salary, dtype: float64

### 6️⃣ Backward Fill

In [16]:
df["Salary"].bfill()

0    90000.0
1    75000.0
2    95000.0
3    95000.0
4    65000.0
5        NaN
Name: Salary, dtype: float64

In [17]:
df["Department"].fillna(
    df["Department"].mode()[0]
)

0      AI
1    Data
2      AI
3      AI
4     Web
5    Data
Name: Department, dtype: object