# 🐼 Pandas Data-Cleaning Mini Project

### Dataset

In [44]:
import pandas as pd
import numpy as np

employees = {
    "ID": [301, 302, 303, 304, 305, 306, 307, 308, 309, 310],
    "Name": [
        "Aarav", "Meera", "Rohan", "Priya", "Arjun",
        "Ananya", "Kabir", "Ishita", "Rahul", "Sneha"
    ],
    "Department": [
        "AI", "Data", "AI", np.nan, "Web",
        "AI", "Data", "Data", np.nan, "AI"
    ],
    "Age": [
        24, 27, np.nan, 31, 26,
        np.nan, 29, 25, 28, 23
    ],
    "Salary": [
        78000, 85000, 92000, np.nan, 68000,
        88000, np.nan, 76000, 150000, 82000
    ],
    "Experience": [
        1, 3, 5, 7, np.nan,
        2, 4, np.nan, 6, 1
    ],
    "Performance": [
        82, 91, 88, 95, np.nan,
        84, 79, 93, 97, np.nan
    ]
}

df = pd.DataFrame(employees)

print(df)

    ID    Name Department   Age    Salary  Experience  Performance
0  301   Aarav         AI  24.0   78000.0         1.0         82.0
1  302   Meera       Data  27.0   85000.0         3.0         91.0
2  303   Rohan         AI   NaN   92000.0         5.0         88.0
3  304   Priya        NaN  31.0       NaN         7.0         95.0
4  305   Arjun        Web  26.0   68000.0         NaN          NaN
5  306  Ananya         AI   NaN   88000.0         2.0         84.0
6  307   Kabir       Data  29.0       NaN         4.0         79.0
7  308  Ishita       Data  25.0   76000.0         NaN         93.0
8  309   Rahul        NaN  28.0  150000.0         6.0         97.0
9  310   Sneha         AI  23.0   82000.0         1.0          NaN

### 🔧 Part 1 — Data Cleaning

In [45]:
clean_df = df.copy()

clean_df

    ID    Name Department   Age    Salary  Experience  Performance
0  301   Aarav         AI  24.0   78000.0         1.0         82.0
1  302   Meera       Data  27.0   85000.0         3.0         91.0
2  303   Rohan         AI   NaN   92000.0         5.0         88.0
3  304   Priya        NaN  31.0       NaN         7.0         95.0
4  305   Arjun        Web  26.0   68000.0         NaN          NaN
5  306  Ananya         AI   NaN   88000.0         2.0         84.0
6  307   Kabir       Data  29.0       NaN         4.0         79.0
7  308  Ishita       Data  25.0   76000.0         NaN         93.0
8  309   Rahul        NaN  28.0  150000.0         6.0         97.0
9  310   Sneha         AI  23.0   82000.0         1.0          NaN

In [46]:
clean_df["Department"] = clean_df["Department"].fillna(
    clean_df["Department"].mode()[0]
)

In [47]:
clean_df["Age"] = clean_df["Age"].fillna(
    clean_df["Age"].mean()
)

In [48]:
clean_df["Salary"] = clean_df["Salary"].fillna(
    clean_df["Salary"].median()
)

In [49]:
clean_df["Experience"] = clean_df["Experience"].fillna(
    clean_df["Experience"].mean()
)

In [50]:
clean_df["Performance"] = clean_df["Performance"].fillna(
    clean_df["Performance"].mean()
)

In [51]:
clean_df.isnull().sum()

ID             0
Name           0
Department     0
Age            0
Salary         0
Experience     0
Performance    0
dtype: int64

### 🧮 Part 2 — Feature Engineering

In [52]:
clean_df["Annual_Bonus"] = np.where(
    clean_df["Salary"] >= 90000,
    10000,
    5000
)

clean_df.head()

,ID,Name,Department,Age,Salary,Experience,Performance,Annual_Bonus
0,301,Aarav,AI,24.000,78000.0,1.000,82.000,5000
1,302,Meera,Data,27.000,85000.0,3.000,91.000,5000
2,303,Rohan,AI,26.625,92000.0,5.000,88.000,10000
3,304,Priya,AI,31.000,83500.0,7.000,95.000,5000
4,305,Arjun,Web,26.000,68000.0,3.625,88.625,5000

In [53]:
clean_df["Total_Compensation"] = clean_df["Salary"] + clean_df["Annual_Bonus"]

clean_df.head()

,ID,Name,Department,Age,Salary,Experience,Performance,Annual_Bonus,Total_Compensation
0,301,Aarav,AI,24.000,78000.0,1.000,82.000,5000,83000.0
1,302,Meera,Data,27.000,85000.0,3.000,91.000,5000,90000.0
2,303,Rohan,AI,26.625,92000.0,5.000,88.000,10000,102000.0
3,304,Priya,AI,31.000,83500.0,7.000,95.000,5000,88500.0
4,305,Arjun,Web,26.000,68000.0,3.625,88.625,5000,73000.0

In [54]:
clean_df["Performance_Level"] = np.where(
    clean_df["Performance"] >= 90,
    "Excellent",
    np.where(
        clean_df["Performance"] >= 80,
        "Good",
        "Needs Improvement"
    )
)

clean_df.head()

,ID,Name,Department,Age,Salary,Experience,Performance,Annual_Bonus,Total_Compensation,Performance_Level
0,301,Aarav,AI,24.000,78000.0,1.000,82.000,5000,83000.0,Good
1,302,Meera,Data,27.000,85000.0,3.000,91.000,5000,90000.0,Excellent
2,303,Rohan,AI,26.625,92000.0,5.000,88.000,10000,102000.0,Good
3,304,Priya,AI,31.000,83500.0,7.000,95.000,5000,88500.0,Excellent
4,305,Arjun,Web,26.000,68000.0,3.625,88.625,5000,73000.0,Good

### 🔎 Part 3 — Data Analysis

In [67]:
clean_df.sort_values(
    "Salary",
    ascending=False
)[["Name", "Department", "Salary", "Experience"]].head(5)

     Name Department    Salary  Experience
8   Rahul         AI  150000.0         6.0
2   Rohan         AI   92000.0         5.0
5  Ananya         AI   88000.0         2.0
1   Meera       Data   85000.0         3.0
3   Priya         AI   83500.0         7.0

In [56]:
clean_df.sort_values(
    "Performance",
    ascending=False
)[["Name", "Performance", "Department"]].head(3)

     Name  Performance Department
8   Rahul         97.0         AI
3   Priya         95.0         AI
7  Ishita         93.0       Data

In [57]:
clean_df[(clean_df["Salary"] >= 85000) & (clean_df["Performance"] >= 85)]

,ID,Name,Department,Age,Salary,Experience,Performance,Annual_Bonus,Total_Compensation,Performance_Level
1,302,Meera,Data,27.000,85000.0,3.0,91.0,5000,90000.0,Excellent
2,303,Rohan,AI,26.625,92000.0,5.0,88.0,10000,102000.0,Good
8,309,Rahul,AI,28.000,150000.0,6.0,97.0,10000,160000.0,Excellent

In [58]:
clean_df[(clean_df["Experience"] >= 3) & (clean_df["Performance"] >= 90)].sort_values(
    "Performance",
    ascending=False
)

,ID,Name,Department,Age,Salary,Experience,Performance,Annual_Bonus,Total_Compensation,Performance_Level
8,309,Rahul,AI,28.0,150000.0,6.000,97.0,10000,160000.0,Excellent
3,304,Priya,AI,31.0,83500.0,7.000,95.0,5000,88500.0,Excellent
7,308,Ishita,Data,25.0,76000.0,3.625,93.0,5000,81000.0,Excellent
1,302,Meera,Data,27.0,85000.0,3.000,91.0,5000,90000.0,Excellent

### 🏢 Part 4 — Department Analysis

In [59]:
clean_df[clean_df["Department"] == "AI"].sort_values(
    "Salary",
    ascending=False
)

,ID,Name,Department,Age,Salary,Experience,Performance,Annual_Bonus,Total_Compensation,Performance_Level
8,309,Rahul,AI,28.000,150000.0,6.0,97.000,10000,160000.0,Excellent
2,303,Rohan,AI,26.625,92000.0,5.0,88.000,10000,102000.0,Good
5,306,Ananya,AI,26.625,88000.0,2.0,84.000,5000,93000.0,Good
3,304,Priya,AI,31.000,83500.0,7.0,95.000,5000,88500.0,Excellent
9,310,Sneha,AI,23.000,82000.0,1.0,88.625,5000,87000.0,Good
0,301,Aarav,AI,24.000,78000.0,1.0,82.000,5000,83000.0,Good

In [60]:
print(clean_df[clean_df["Department"] == "AI"]["Salary"].mean().round(2))
print()
print(clean_df[clean_df["Department"] == "Data"]["Salary"].mean().round(2))
print()
print(clean_df[clean_df["Department"] == "Web"]["Salary"].mean().round(2))
print()

95583.33

81500.0

68000.0

In [61]:
clean_df[clean_df["Department"] == "AI"].sort_values(
    "Salary",
    ascending=False
).head(1)

,ID,Name,Department,Age,Salary,Experience,Performance,Annual_Bonus,Total_Compensation,Performance_Level
8,309,Rahul,AI,28.0,150000.0,6.0,97.0,10000,160000.0,Excellent

In [62]:
clean_df[clean_df["Department"] == "Data"].sort_values(
    "Salary",
    ascending=False
).head(1)

,ID,Name,Department,Age,Salary,Experience,Performance,Annual_Bonus,Total_Compensation,Performance_Level
1,302,Meera,Data,27.0,85000.0,3.0,91.0,5000,90000.0,Excellent

In [63]:
clean_df[clean_df["Department"] == "Web"].sort_values(
    "Salary",
    ascending=False
).head(1)

,ID,Name,Department,Age,Salary,Experience,Performance,Annual_Bonus,Total_Compensation,Performance_Level
4,305,Arjun,Web,26.0,68000.0,3.625,88.625,5000,73000.0,Good

### 🔥 Part 5 — Final Challenge

In [65]:
top_performers = clean_df[
    (clean_df["Salary"] >= 85000) & 
    (clean_df["Performance"] >= 85) & 
    (clean_df["Experience"] >= 3)
].sort_values(
    "Performance",
    ascending=False
)[[
    "Name", 
    "Department", 
    "Salary", 
    "Experience", 
    "Performance", 
    "Performance_Level", 
    "Total_Compensation"
]]

top_performers

,Name,Department,Salary,Experience,Performance,Performance_Level,Total_Compensation
8,Rahul,AI,150000.0,6.0,97.0,Excellent,160000.0
1,Meera,Data,85000.0,3.0,91.0,Excellent,90000.0
2,Rohan,AI,92000.0,5.0,88.0,Good,102000.0

# 🏆 Bonus Challenge

In [ ]:
clean_df.sort_values(
    "Total_Compensation",
    ascending=False
).head(1)

,ID,Name,Department,Age,Salary,Experience,Performance,Annual_Bonus,Total_Compensation,Performance_Level
8,309,Rahul,AI,28.0,150000.0,6.0,97.0,10000,160000.0,Excellent

In [ ]:
clean_df.sort_values(
    "Total_Compensation"
).head(1)

,ID,Name,Department,Age,Salary,Experience,Performance,Annual_Bonus,Total_Compensation,Performance_Level
4,305,Arjun,Web,26.0,68000.0,3.625,88.625,5000,73000.0,Good

In [66]:
clean_df.groupby("Department")["Total_Compensation"].mean().sort_values(
    ascending=False
)

Department
AI      102250.0
Data     86500.0
Web      73000.0
Name: Total_Compensation, dtype: float64