# 🐼 Filtering

In [1]:
import pandas as pd

students = {
    "ID": [101, 102, 103, 104, 105],
    "Name": ["Harpit", "Luffy", "Zoro", "Naruto", "Sanji"],
    "Age": [21, 19, 21, 20, 22],
    "Python": [92, 85, 78, 95, 88],
    "ML": [90, 80, 82, 96, 91]
}

df = pd.DataFrame(students)

### Boolean Mask

In [2]:
df["Age"] > 20

0     True
1    False
2     True
3    False
4     True
Name: Age, dtype: bool

In [3]:
df[df["Age"] > 20]

    ID    Name  Age  Python  ML
0  101  Harpit   21      92  90
2  103    Zoro   21      78  82
4  105   Sanji   22      88  91

In [4]:
df[df["Age"] < 21]

    ID    Name  Age  Python  ML
1  102   Luffy   19      85  80
3  104  Naruto   20      95  96

In [5]:
df[df["Python"] >= 90]

    ID    Name  Age  Python  ML
0  101  Harpit   21      92  90
3  104  Naruto   20      95  96

In [6]:
df[df["ML"] <= 85]

    ID   Name  Age  Python  ML
1  102  Luffy   19      85  80
2  103   Zoro   21      78  82

In [7]:
df[df["Age"] == 21]

    ID    Name  Age  Python  ML
0  101  Harpit   21      92  90
2  103    Zoro   21      78  82

In [8]:
df[df["Age"] != 21]

    ID    Name  Age  Python  ML
1  102   Luffy   19      85  80
3  104  Naruto   20      95  96
4  105   Sanji   22      88  91

### 🌟 Multiple Conditions

In [9]:
df[(df["Age"] > 20) & (df["Python"] > 90)]

    ID    Name  Age  Python  ML
0  101  Harpit   21      92  90

### OR Condition

In [10]:
df[(df["Age"] == 19) | (df["Python"] > 90)]

    ID    Name  Age  Python  ML
0  101  Harpit   21      92  90
1  102   Luffy   19      85  80
3  104  Naruto   20      95  96

### AND Condition

In [11]:
df[(df["Age"] > 20) & (df["Python"] > 90)]

    ID    Name  Age  Python  ML
0  101  Harpit   21      92  90