# 🐼 Mini Project — Employee Data Analysis

In [1]:
import pandas as pd

employees = {
    "ID": [101,102,103,104,105,106,107],
    "Name": ["Alice","Bob","Charlie","David","Eva","Frank","Grace"],
    "Department": ["AI","Web","AI","Data","Web","AI","Data"],
    "Age": [24,28,26,30,25,29,27],
    "Salary": [90000,70000,85000,95000,65000,92000,88000],
    "Experience": [2,4,3,6,1,5,4]
}

df = pd.DataFrame(employees)

### 🟢 Task 1 — Inspect the Dataset

In [29]:
print(df.head())
print()

print(df.tail())
print()

print(df.shape)
print()

print(df.columns)
print()

print(df.index)
print()

print(df.dtypes)
print()

df.info()
print()

print(df.describe())
print()

    ID     Name Department  Age  Salary  Experience  Bonus
0  101    Alice         AI   24   90000           2  10000
1  102      Bob        Web   28   70000           4   5000
2  103  Charlie         AI   26   85000           3   5000
3  104    David       Data   30   95000           6  10000
4  105      Eva        Web   25   65000           1   5000

    ID     Name Department  Age  Salary  Experience  Bonus
2  103  Charlie         AI   26   85000           3   5000
3  104    David       Data   30   95000           6  10000
4  105      Eva        Web   25   65000           1   5000
5  106    Frank         AI   29   92000           5  10000
6  107    Grace       Data   27   88000           4   5000

(7, 7)

Index(['ID', 'Name', 'Department', 'Age', 'Salary', 'Experience', 'Bonus'], dtype='object')

RangeIndex(start=0, stop=7, step=1)

ID             int64
Name          object
Department    object
Age            int64
Salary         int64
Experience     int64
Bonus          int64
dtype: object

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 7 entries, 0 to 6
Data columns (total 7 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   ID          7 non-null      int64
 1   Name        7 non-null      object
 2   Department  7 non-null      object
 3   Age         7 non-null      int64
 4   Salary      7 non-null      int64
 5   Experience  7 non-null      int64
 6   Bonus       7 non-null      int64
dtypes: int64(5), object(2)
memory usage: 524.0+ bytes

               ID        Age        Salary  Experience         Bonus
count    7.000000   7.000000      7.000000    7.000000      7.000000
mean   104.000000  27.000000  83571.428571    3.571429   7142.857143
std      2.160247   2.160247  11501.552690    1.718249   2672.612419
min    101.000000  24.000000  65000.000000    1.000000   5000.000000
25%    102.500000  25.500000  77500.000000    2.500000   5000.000000
50%    104.000000  27.000000  88000.000000    4.000000   5000.000000
75%    105.500000  28.500000  91000.000000    4.500000  10000.000000
max    107.000000  30.000000  95000.000000    6.000000  10000.000000

### 🟢 Task 2 — Basic Questions

### Answer:

##### How many employees are there? -> 7
##### Which columns contain text? -> ["Name", "Department"]
##### Average salary? -> 83571.428571
##### Highest salary? -> 95000
##### Lowest salary? -> 65000
##### Average experience? -> 3.571429

### 🟢 Task 3 — Column Selection

In [3]:
df["Name"]

0      Alice
1        Bob
2    Charlie
3      David
4        Eva
5      Frank
6      Grace
Name: Name, dtype: object

In [4]:
df["Department"]

0      AI
1     Web
2      AI
3    Data
4     Web
5      AI
6    Data
Name: Department, dtype: object

In [5]:
df["Salary"]

0    90000
1    70000
2    85000
3    95000
4    65000
5    92000
6    88000
Name: Salary, dtype: int64

In [6]:
df[["Name", "Salary"]]

      Name  Salary
0    Alice   90000
1      Bob   70000
2  Charlie   85000
3    David   95000
4      Eva   65000
5    Frank   92000
6    Grace   88000

In [7]:
df[["Name", "Department", "Salary"]]

      Name Department  Salary
0    Alice         AI   90000
1      Bob        Web   70000
2  Charlie         AI   85000
3    David       Data   95000
4      Eva        Web   65000
5    Frank         AI   92000
6    Grace       Data   88000

### 🟢 Task 4 — iloc Practice

In [8]:
df.iloc[0]

ID              101
Name          Alice
Department       AI
Age              24
Salary        90000
Experience        2
Name: 0, dtype: object

In [9]:
df.iloc[2]

ID                103
Name          Charlie
Department         AI
Age                26
Salary          85000
Experience          3
Name: 2, dtype: object

In [10]:
df.iloc[:3]

    ID     Name Department  Age  Salary  Experience
0  101    Alice         AI   24   90000           2
1  102      Bob        Web   28   70000           4
2  103  Charlie         AI   26   85000           3

In [11]:
df.iloc[-2:]

    ID   Name Department  Age  Salary  Experience
5  106  Frank         AI   29   92000           5
6  107  Grace       Data   27   88000           4

In [12]:
df.iloc[:, [1, 2, 4]]

      Name Department  Salary
0    Alice         AI   90000
1      Bob        Web   70000
2  Charlie         AI   85000
3    David       Data   95000
4      Eva        Web   65000
5    Frank         AI   92000
6    Grace       Data   88000

### 🟢 Task 5 — loc Practice

In [13]:
print(df.loc[1,"Salary"])

70000

In [14]:
print(df.loc[5,"Department"])

AI

In [15]:
print(df.loc[3])

ID              104
Name          David
Department     Data
Age              30
Salary        95000
Experience        6
Name: 3, dtype: object

### 🟢 Task 6 — Filtering

In [16]:
df[df["Age"] > 26]

    ID   Name Department  Age  Salary  Experience
1  102    Bob        Web   28   70000           4
3  104  David       Data   30   95000           6
5  106  Frank         AI   29   92000           5
6  107  Grace       Data   27   88000           4

In [17]:
df[df["Salary"] > 85000]

    ID   Name Department  Age  Salary  Experience
0  101  Alice         AI   24   90000           2
3  104  David       Data   30   95000           6
5  106  Frank         AI   29   92000           5
6  107  Grace       Data   27   88000           4

In [18]:
df[df["Department"] == "AI"]

    ID     Name Department  Age  Salary  Experience
0  101    Alice         AI   24   90000           2
2  103  Charlie         AI   26   85000           3
5  106    Frank         AI   29   92000           5

In [19]:
df[df["Department"] == "Web"]

    ID Name Department  Age  Salary  Experience
1  102  Bob        Web   28   70000           4
4  105  Eva        Web   25   65000           1

In [20]:
df[df["Experience"] == 4]

    ID   Name Department  Age  Salary  Experience
1  102    Bob        Web   28   70000           4
6  107  Grace       Data   27   88000           4

In [21]:
df[df["Salary"] < 80000]

    ID Name Department  Age  Salary  Experience
1  102  Bob        Web   28   70000           4
4  105  Eva        Web   25   65000           1

### 🟢 Task 7 — Multiple Conditions

In [22]:
df[(df["Department"] == "AI") & (df["Salary"] > 90000)]

    ID   Name Department  Age  Salary  Experience
5  106  Frank         AI   29   92000           5

In [23]:
df[(df["Department"] == "Data") & (df["Experience"] >= 4)]

    ID   Name Department  Age  Salary  Experience
3  104  David       Data   30   95000           6
6  107  Grace       Data   27   88000           4

In [24]:
df[(df["Department"] == "Web") | (df["Salary"] < 70000)]

    ID Name Department  Age  Salary  Experience
1  102  Bob        Web   28   70000           4
4  105  Eva        Web   25   65000           1

In [25]:
df[(df["Age"] > 25) & (df["Experience"] > 3)]

    ID   Name Department  Age  Salary  Experience
1  102    Bob        Web   28   70000           4
3  104  David       Data   30   95000           6
5  106  Frank         AI   29   92000           5
6  107  Grace       Data   27   88000           4

### 🟢 Task 8 — Statistics

In [26]:
print(df["Salary"].mean())

print(df["Salary"].max())

print(df["Salary"].min())

print(df["Experience"].mean())

print(df["Age"].mean())

83571.42857142857
95000
65000
3.5714285714285716
27.0

### 🌟 Bonus Challenge

In [27]:
bonus = []

for salary in df["Salary"]:
    if salary >= 90000:
        bonus.append(10000)
    else:
        bonus.append(5000)

df["Bonus"] = bonus

In [28]:
df.head()

    ID     Name Department  Age  Salary  Experience  Bonus
0  101    Alice         AI   24   90000           2  10000
1  102      Bob        Web   28   70000           4   5000
2  103  Charlie         AI   26   85000           3   5000
3  104    David       Data   30   95000           6  10000
4  105      Eva        Web   25   65000           1   5000