# 🐼 Final Pandas Tools: merge(), concat(), CSV

In [12]:
import pandas as pd

employees = pd.DataFrame({
    "ID": [101, 102, 103],
    "Name": ["Alice", "Bob", "Charlie"]
})

salary = pd.DataFrame({
    "ID": [101, 102, 103],
    "Salary": [90000, 70000, 85000]
})

employees2 = pd.DataFrame({
    "ID": [104, 105],
    "Name": ["David", "Eva"]
})

In [13]:
merged = employees.merge(
    salary,
    on="ID"
)
merged

    ID     Name  Salary
0  101    Alice   90000
1  102      Bob   70000
2  103  Charlie   85000

In [14]:
merged = pd.concat(
    [merged, employees2],
    ignore_index=True
)
merged

    ID     Name   Salary
0  101    Alice  90000.0
1  102      Bob  70000.0
2  103  Charlie  85000.0
3  104    David      NaN
4  105      Eva      NaN

In [15]:
merged.to_csv("employees_with_salary.csv", index=False)

In [17]:
loaded = pd.read_csv("employees_with_salary.csv")
loaded

    ID     Name   Salary
0  101    Alice  90000.0
1  102      Bob  70000.0
2  103  Charlie  85000.0
3  104    David      NaN
4  105      Eva      NaN