# 🎯 Mini Integration Project

### Dataset 1 — Employee Information

In [31]:
import pandas as pd
import numpy as np

employees = pd.DataFrame({
    "ID": [101, 102, 103, 104, 105, 106],
    "Name": [
        "Alice", "Bob", "Charlie",
        "David", "Eva", "Frank"
    ],
    "Department": [
        "AI", "Data", "AI",
        "Web", "Data", "AI"
    ],
    "Age": [24, 28, 26, 30, 25, 29]
})

### Dataset 2 — Salary Information

In [32]:
salary = pd.DataFrame({
    "ID": [101, 102, 103, 104, 105, 106],
    "Salary": [
        90000, 70000, 85000,
        95000, 65000, 92000
    ],
    "Experience": [2, 4, 3, 6, 1, 5]
})

### Dataset 3 — Performance Information

In [33]:
performance = pd.DataFrame({
    "ID": [101, 102, 103, 104, 105, 106],
    "Performance": [92, 81, 88, 95, 79, 90]
})

### 🟢 Task 1 — Merge the Data

In [34]:
merged = employees.merge(
    salary,
    on="ID"
)

In [35]:
merged = merged.merge(
    performance,
    on="ID"
)

### 🟢 Task 2 — Inspect

In [36]:
merged.head()

    ID     Name Department  Age  Salary  Experience  Performance
0  101    Alice         AI   24   90000           2           92
1  102      Bob       Data   28   70000           4           81
2  103  Charlie         AI   26   85000           3           88
3  104    David        Web   30   95000           6           95
4  105      Eva       Data   25   65000           1           79

In [37]:
print(merged.shape)

(6, 7)

In [38]:
print(merged.dtypes)

ID              int64
Name           object
Department     object
Age             int64
Salary          int64
Experience      int64
Performance     int64
dtype: object

### 🟢 Task 3 — Create Features

In [39]:
merged["Annual_Bonus"] = np.where(
    merged["Salary"] >= 90000,
    10000,
    5000
)

merged["Total_Compensation"] = merged["Salary"] + merged["Annual_Bonus"]

merged["Performance_Level"] = np.where(
    merged["Performance"] >= 90,
    "Excellent",
    np.where(
        merged["Performance"] >= 80,
        "Good",
        "Needs Improvement"
    )
)

In [40]:
merged

,ID,Name,Department,Age,Salary,Experience,Performance,Annual_Bonus,Total_Compensation,Performance_Level
0,101,Alice,AI,24,90000,2,92,10000,100000,Excellent
1,102,Bob,Data,28,70000,4,81,5000,75000,Good
2,103,Charlie,AI,26,85000,3,88,5000,90000,Good
3,104,David,Web,30,95000,6,95,10000,105000,Excellent
4,105,Eva,Data,25,65000,1,79,5000,70000,Needs Improvement
5,106,Frank,AI,29,92000,5,90,10000,102000,Excellent

### 🟢 Task 4 — Filtering

In [41]:
merged[(merged["Salary"] >= 85000) & (merged["Performance"] >= 85)]

,ID,Name,Department,Age,Salary,Experience,Performance,Annual_Bonus,Total_Compensation,Performance_Level
0,101,Alice,AI,24,90000,2,92,10000,100000,Excellent
2,103,Charlie,AI,26,85000,3,88,5000,90000,Good
3,104,David,Web,30,95000,6,95,10000,105000,Excellent
5,106,Frank,AI,29,92000,5,90,10000,102000,Excellent

### 🟢 Task 5 — Top Employees

In [42]:
merged.sort_values(
    "Total_Compensation",
    ascending=False
)[[
    "Name",
    "Department",
    "Salary",
    "Total_Compensation"
]].head(3)

    Name Department  Salary  Total_Compensation
3  David        Web   95000              105000
5  Frank         AI   92000              102000
0  Alice         AI   90000              100000

### 🟢 Task 6 — Department Analysis

In [43]:
summary = merged.groupby("Department").agg(
    Employee_Count=("ID", "count"),
    Average_Salary=("Salary", "mean"),
    Average_Performance=("Performance", "mean"),
    Maximum_Salary=("Salary", "max")
)

summary = summary.sort_values(
    "Average_Salary",
    ascending=False
)

In [44]:
summary

,Employee_Count,Average_Salary,Average_Performance,Maximum_Salary
Department,,,,
Web,1,95000.0,95.0,95000
AI,3,89000.0,90.0,92000
Data,2,67500.0,80.0,70000

### 🟢 Task 7 — Concat Practice

In [45]:
new_employees = pd.DataFrame({
    "ID": [107, 108],
    "Name": ["Grace", "Henry"],
    "Department": ["Data", "AI"],
    "Age": [27, 31]
})

employees1 = pd.concat(
    [employees, new_employees],
    ignore_index=True
)

employees1

    ID     Name Department  Age
0  101    Alice         AI   24
1  102      Bob       Data   28
2  103  Charlie         AI   26
3  104    David        Web   30
4  105      Eva       Data   25
5  106    Frank         AI   29
6  107    Grace       Data   27
7  108    Henry         AI   31

### 🟢 Task 8 — Handle the New Batch

In [48]:
new_salary = pd.DataFrame({
    "ID": [107, 108],
    "Salary": [88000, 97000],
    "Experience": [4, 7]
})

new_performance = pd.DataFrame({
    "ID": [107, 108],
    "Performance": [91, 94]
})

employees2 = employees1.merge(
    new_salary,
    on="ID"
)

print(employees1)

employees2 = employees1.merge(
    new_performance,
    on="ID"
)

    ID   Name Department  Age  Salary  Experience
0  107  Grace       Data   27   88000           4
1  108  Henry         AI   31   97000           7

In [49]:
employees2

    ID   Name Department  Age  Salary  Experience  Performance
0  107  Grace       Data   27   88000           4           91
1  108  Henry         AI   31   97000           7           94

### 🔥 Task 9 — Final Combined Dataset

In [52]:
df = employees.merge(salary, on="ID")
df = df.merge(performance, on="ID")

new_df = new_employees.merge(new_salary, on="ID")
new_df = new_df.merge(new_performance, on="ID")

final_df = pd.concat([df, new_df], ignore_index=True)

In [53]:
final_df

    ID     Name Department  Age  Salary  Experience  Performance
0  101    Alice         AI   24   90000           2           92
1  102      Bob       Data   28   70000           4           81
2  103  Charlie         AI   26   85000           3           88
3  104    David        Web   30   95000           6           95
4  105      Eva       Data   25   65000           1           79
5  106    Frank         AI   29   92000           5           90
6  107    Grace       Data   27   88000           4           91
7  108    Henry         AI   31   97000           7           94

In [54]:
final_df["Annual_Bonus"] = np.where(
    final_df["Salary"] >= 90000,
    10000,
    5000
)

final_df["Total_Compensation"] = (
    final_df["Salary"] + final_df["Annual_Bonus"]
)

In [58]:
final_df["Performance_Level"] = np.where(
    final_df["Performance"] >= 90,
    "Excellent",
    np.where(
        final_df["Performance"] >= 80,
        "Good",
        "Needs Improvement"
    )
)

final_df = final_df.sort_values(
    "Total_Compensation",
    ascending=False
)

final_df

,ID,Name,Department,Age,Salary,Experience,Performance,Annual_Bonus,Total_Compensation,Performance_Level
7,108,Henry,AI,31,97000,7,94,10000,107000,Excellent
3,104,David,Web,30,95000,6,95,10000,105000,Excellent
5,106,Frank,AI,29,92000,5,90,10000,102000,Excellent
0,101,Alice,AI,24,90000,2,92,10000,100000,Excellent
6,107,Grace,Data,27,88000,4,91,5000,93000,Excellent
2,103,Charlie,AI,26,85000,3,88,5000,90000,Good
1,102,Bob,Data,28,70000,4,81,5000,75000,Good
4,105,Eva,Data,25,65000,1,79,5000,70000,Needs Improvement

### 🔥 Task 10 — Save It

In [57]:
final_df.to_csv("employee_analysis.csv", index=False)

In [59]:
loaded = pd.read_csv("employee_analysis.csv")
loaded

,ID,Name,Department,Age,Salary,Experience,Performance,Annual_Bonus,Total_Compensation,Performance_Level
0,108,Henry,AI,31,97000,7,94,10000,107000,Excellent
1,104,David,Web,30,95000,6,95,10000,105000,Excellent
2,106,Frank,AI,29,92000,5,90,10000,102000,Excellent
3,101,Alice,AI,24,90000,2,92,10000,100000,Excellent
4,107,Grace,Data,27,88000,4,91,5000,93000,Excellent
5,103,Charlie,AI,26,85000,3,88,5000,90000,Good
6,102,Bob,Data,28,70000,4,81,5000,75000,Good
7,105,Eva,Data,25,65000,1,79,5000,70000,Needs Improvement